In [15]:
import pandas as pd 
import scsims
from sklearn.preprocessing import LabelEncoder
import sys

sys.path.append('../src')
sys.path.append('../tests')
from models.lib.lightning_train import DataModule, generate_trainer
from models.lib.neural import GeneClassifier
from models.lib.data import *

Let's do some simple preprocessing for training, and then test our library

In [2]:
# le = LabelEncoder()

# labels = pd.read_csv('../data/retina/retina_labels.tsv', sep='\t')
# labels = labels[labels['CellType'] != 'unannotated']
# labels['class_label'] = le.fit_transform(labels['CellType'])
# labels.index.name = 'cell'

# labels.to_csv('../data/retina/retina_labels_numeric.csv')

label_df = pd.read_csv('../data/retina/retina_labels_numeric.csv', index_col='cell')
label_df

index  Expressed Genes  UMI Count  \
cell                                                                  
0      0024369980fd003553cbc9dfe29f7f95             2351     6060.0   
2      0037f1b36684cb59b84d3585ca55ff69              950     1507.0   
3      00390952646f52d11a9ab9bba7d6ac51              961     1962.0   
4      005b3351658380695a5dc46c384d72d7              858     1384.0   
6      00906832f470fc434a52ac7d678a95bc              532     1054.0   
...                                 ...              ...        ...   
19684  ff61c0c282f41e4a37885b05342441da             1494     3320.0   
19689  ffa4633bef82949d2c6ac17b3ddf46e9             1813     4129.0   
19690  ffa5758b0600f47722fdc755444dfe0c             2692     8244.0   
19691  ffd3fd6119de767f3c3b8c47b2c28bf0              516      896.0   
19693  fffd3d11e75c6c544e6741967b3edb7a             1896     4175.0   

       Percent Mitochond.      BroadCellType                 CellType  \
cell                                                                    
0                4.125413   retinal rod cell  retinal rod cell type A   
2                0.597213   retinal rod cell  retinal rod cell type B   
3                7.543323   retinal rod cell  retinal rod cell type A   
4                0.144509   retinal rod cell  retinal rod cell type B   
6                6.451613   retinal rod cell  retinal rod cell type A   
...                   ...                ...                      ...   
19684            2.289157   retinal rod cell  retinal rod cell type B   
19689            3.996125   retinal rod cell  retinal rod cell type A   
19690           16.460457  retinal cone cell        retinal cone cell   
19691            3.794643   retinal rod cell  retinal rod cell type A   
19693            4.550898   retinal rod cell  retinal rod cell type A   

                                      Donor  class_label  
cell                                                      
0      b8049daa-7458-47bf-8ec2-3f5c56d2cb34            9  
2      427c0a62-9baf-42ab-a3a3-f48d10544280           10  
3      b8049daa-7458-47bf-8ec2-3f5c56d2cb34            9  
4      b8049daa-7458-47bf-8ec2-3f5c56d2cb34           10  
6      427c0a62-9baf-42ab-a3a3-f48d10544280            9  
...                                     ...          ...  
19684  427c0a62-9baf-42ab-a3a3-f48d10544280           10  
19689  b8049daa-7458-47bf-8ec2-3f5c56d2cb34            9  
19690  b8049daa-7458-47bf-8ec2-3f5c56d2cb34            7  
19691  427c0a62-9baf-42ab-a3a3-f48d10544280            9  
19693  b8049daa-7458-47bf-8ec2-3f5c56d2cb34            9  

[16446 rows x 8 columns]

In [3]:
datafiles = ['../data/retina/retina_T.csv']
labelfiles = ['../data/retina/retina_labels_numeric.csv']

module = DataModule(
    datafiles=['../data/retina/retina_T.csv'],
    labelfiles=['../data/retina/retina_labels_numeric.csv'],
    class_label='class_label',
    batch_size=4,
    num_workers=0,
    skip=3,
    shuffle=True,
    drop_last=True,
    index_col='cell',
)

In [4]:
model = GeneClassifier(
    input_dim=module.num_features,
    output_dim=module.num_labels,
    weights=None
)

Model initialized. input_dim = 37475, output_dim = 13. Metrics are dict_keys(['accuracy', 'precision', 'recall']) and weighted_metrics = False


In [5]:
trainer, model, module = generate_trainer(
    datafiles=['../data/retina/retina_T.csv'],
    labelfiles=['../data/retina/retina_labels_numeric.csv'],
    class_label='class_label',
    index_col='cell',
    batch_size=4,
    num_workers=0,
    skip=3,
    shuffle=True,
    drop_last=True,
    weighted_metrics=False,
    normalize=True,
)

trainer.fit(model, datamodule=module)

Device is cpu
../data/retina/retina_T.csv exists, continuing...
../data/retina/retina_labels_numeric.csv exists, continuing...



GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs


Model initialized. input_dim = 37475, output_dim = 13. Metrics are dict_keys(['accuracy', 'precision', 'recall']) and weighted_metrics = False


In [7]:
module.setup()

trainloader = module.trainloader

Creating train/val/test DataLoaders...
Extension .csv not recognized,                 interpreting as .csv. To silence this warning, pass in explicit file types.
Done, continuing to training.


In [19]:
trainloader.dataset[0:50]

[(tensor([0., 1., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 9),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 9),
 (tensor([0., 1., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 3),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 1),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 5),
 (tensor([0., 1., 0.,  ..., 0., 0., 0.]), 9),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 9),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 1., 0.,  ..., 0., 0., 0.]), 9),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 9),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 11),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 7),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 11),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 2., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 0., 0.,  ..., 0., 0., 0.]), 10),
 (tensor([0., 0., 0.,  

In [17]:
def _test_first_n_samples(n, datafile, labelfile):
    data = GeneExpressionData(
        datafile, 
        labelfile, 
        'class_label', 
        skip=3,
        index_col='cell'
    )
    cols = data.columns
    
    # Generate dict with half precision values to read this into my 16gb memory
    dtype_cols = dict(zip(cols, [np.float32]*len(cols)))
    
    data_df = pd.read_csv(datafile, nrows=2*n, header=1, dtype=dtype_cols) # Might need some extras since numerical index drops some values
    label_df = pd.read_csv(labelfile, nrows=n)

    similar = []
    for i in range(n):
        datasample = data[i][0]

        dfsample = torch.from_numpy(data_df.loc[label_df.loc[i, 'cell'], :].values).float()
        isclose = all(torch.isclose(datasample, dfsample))
        similar.append(isclose)
    
    print(f"First {n=} columns of expression matrix is equal to GeneExpressionData: {all(p for p in similar)}")

    assert (all(p for p in similar))

_test_first_n_samples(100, '../data/retina/retina_T.csv', '../data/retina/retina_labels_numeric.csv')


First n=100 columns of expression matrix is equal to GeneExpressionData: True


In [ ]:
idk = module.trainloader.dataset._labeldf['cell']
idk

In [ ]:
df = pd.read_csv('../data/retina/retina_labels_numeric.csv')
labels = df.loc[:, 'class_label']

In [ ]:
df.loc[idk, :]

In [ ]:
from sklearn.model_selection import train_test_split 

trainsplit, valsplit = train_test_split(labels, stratify=labels)

trainsplit, valsplit

In [ ]:
df.loc[trainsplit, :]

In [ ]:
df.to_csv('test.csv')

pd.read_csv('test.csv')

In [ ]:
df.to_csv('')