# TabNet Model Test

In this notebook, we'll test a training loop for the TabNet model 


In [1]:
import sys
sys.path.append('../src')

from models.lib.neural import *
from models.lib.data import *
from models.lib.train import *

import helper 
from helper import gene_intersection
from pytorch_tabnet.tab_network import TabNet

import torch.nn as nn 
import torch.optim as optim
import torch
from tqdm import tqdm
from torch.utils.data import Subset
import matplotlib.pyplot as plt 
from models.lib.lightning_train import *

t = helper.INTERIM_DATA_AND_LABEL_FILES_LIST
datafiles, labelfiles = zip(*t.items())
datafiles = [f'../data/interim/{f}' for f in datafiles]
labelfiles = [f'../data/processed/labels/{f}' for f in labelfiles]
refgenes = gene_intersection()

In [2]:
train, val, test = generate_dataloaders(
    datafiles=datafiles, 
    labelfiles=labelfiles, 
    class_label='Type', 
    batch_size=4
)
sample = next(iter(train))
sample

(tensor([[0.0000, 0.0000, 1.9500,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]]),
 tensor([16,  4,  4, 16]))

In [3]:
input_dim=sample[0].shape[1]
output_dim=19

print(input_dim)

19765


In [13]:
model = GeneClassifier(input_dim, output_dim)
model(sample[0])

Model initialized. input_dim = 19765, output_dim = 19. Metrics are dict_keys(['accuracy', 'precision', 'recall']) and weighted_metrics = False


tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436]], grad_fn=<MmBackward0>)

In [14]:
for X, y in train:
    print(model(X))

tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[-0.3562, -1.1428, -1.0016,  0.5114, -0.8077, -0.8802,  2.9606, -0.9653,
          3.5831,  0.3811,  2.7997,  1.4299,  1.4128, -1.6509, -0.2625, -3.4735,
          0.1468, -2.3657,  1.5537],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315],
        [ 1.0153, -0.8452, -3.4839,  1.7611,  4.4167,  2.5938,  1.1916,  1.0082,
          1.6458,  0.6288,  1.6176,  3.4516,  4.4707,  0.7812,  6.1303, -0.3007,
          5.0950, -0.4546,  4.1602],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315]], grad_fn=<MmBackward0>)
tensor([[ 1.3701e+00, -3.5281e+00, -4.6616e+00,  8.0952e-01,  3.0747e-01,
          1.7324e+00,  3.4454e+00, -4.0639e-01,  1.8236e+00,  1.2802e+00,
          1.8928e+00,  3.1591e+0

tensor([[ 4.7172e-01, -1.6895e+00, -1.8998e+00,  1.1912e+00,  1.1933e+00,
          1.4764e+00,  1.7662e+00,  1.0907e-01,  2.4899e+00,  3.6864e-01,
          2.8090e+00,  2.2477e+00,  3.8412e+00, -1.0378e-01,  3.7934e-01,
         -2.2895e+00,  6.9816e-01, -1.6102e+00,  1.3585e+00],
        [-1.9605e-01, -9.5923e-01, -1.0331e+00,  8.1169e-02, -4.2439e-02,
         -8.1186e-01,  5.8467e-01, -1.2242e+00,  1.5515e+00,  1.0983e+00,
          1.3790e+00,  1.9437e+00,  7.2491e-01,  6.5883e-02,  1.5075e-01,
         -1.5701e+00,  5.9695e-01, -4.3395e-01,  2.8611e-03],
        [ 2.2021e-01, -1.1138e+00, -3.0937e+00,  1.6142e+00,  3.2697e+00,
          2.7354e+00,  1.1502e+00,  9.8554e-01,  1.2605e+00,  5.8303e-01,
          1.5041e+00,  2.0115e+00,  3.8434e+00, -1.9040e-01,  3.8624e+00,
         -1.3856e+00,  3.5473e+00, -9.3684e-01,  3.2201e+00],
        [ 1.0855e+00, -1.6392e+00, -1.3318e+00,  7.1761e-02,  6.4441e-01,
          2.9545e-01,  3.0780e+00,  7.8578e-01,  1.4741e+00,  1.1161e+00,


tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436]], grad_fn=<MmBackward0>)
tensor([[ 0.5010, -1.0437, -1.5717,  0.9378,  1.8747, -0.2664,  2.2228, -0.4981,
          3.8039,  1.1878,  3.2865,  4.2082,  1.2977,  0.7474,  1.7347, -2.9200,
          2.9779, 

tensor([[-0.3433, -0.1743, -1.2748,  0.3542,  0.1061, -0.0909,  0.7551, -0.6208,
          1.0039,  0.3619,  0.0995,  0.8748, -0.4875, -0.6766,  1.3666, -0.9213,
          1.6860, -0.8614,  1.1370],
        [ 0.3317, -2.1533, -3.8927,  0.7024, -0.5503,  0.5381,  2.9809, -1.2235,
          2.2321,  0.9484,  0.9304,  2.4795,  0.8032, -0.7502,  1.9707, -2.0133,
          2.7775, -1.8772,  0.8172],
        [-0.3433, -0.1743, -1.2748,  0.3542,  0.1061, -0.0909,  0.7551, -0.6208,
          1.0039,  0.3619,  0.0995,  0.8748, -0.4875, -0.6766,  1.3666, -0.9213,
          1.6860, -0.8614,  1.1370],
        [ 1.2904, -2.5828, -3.7423,  0.8012,  0.6957,  0.6026,  1.8561, -1.3996,
          2.4041,  1.1756,  2.1806,  4.1264,  4.5194,  0.8161,  2.5663, -0.7936,
          1.9016, -0.1409,  0.0991]], grad_fn=<MmBackward0>)
tensor([[ 0.6589, -0.8940, -0.6892,  0.0699,  0.1424, -1.1702,  2.0562, -0.7036,
          2.5340,  0.7702,  2.1257,  2.5968,  0.5715,  0.5702,  0.7185, -1.5629,
          1.1746, 

tensor([[ 0.9483, -2.1977, -3.6224,  1.0148,  0.3303,  2.4494,  1.5367, -0.0963,
          0.6650,  0.4376,  0.3474,  2.1013,  1.6314,  0.5430,  0.8716, -0.6360,
          2.0270, -1.3266, -0.1781],
        [-0.4733,  0.3147, -0.8682,  1.0076,  1.8872,  0.2365,  1.3704,  0.2248,
          2.3890,  0.0877,  1.7477,  1.1570,  1.7507, -1.2837,  2.9156, -1.9140,
          2.3023, -1.3622,  3.7483],
        [ 0.8889, -1.0787, -0.3143,  0.4290,  0.3050, -0.5694,  2.7503, -0.0714,
          3.2636,  0.2584,  3.1835,  2.4067,  1.8854,  0.3305, -0.0997, -2.2219,
          0.3443, -1.9068,  1.4082],
        [ 0.8855, -2.7063, -3.2421, -0.2639, -1.1005, -1.5738,  3.8385, -1.8345,
          2.8000,  1.9455,  1.9058,  3.6713,  0.3197,  0.4087,  1.6904, -2.2527,
          2.5212, -1.2849, -0.1417]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<MmBackward0>)
tensor([[ 0.7533, -0.9046, -0.7475,  0.1401,  0.8960,  0.0853,  1.4806,  0.3648,
          1.0557,  0.5972,  1.4180,  1.5711,  1.1591,  0.8263,  0.9490, -0.7840,
          1.1617, -0.5071,  0.7568],
        [ 1.0421, -1.3354, -1.1182,  0.1676,  0.4093, -0.8924,  4.4559,  0.3825,
          3.1608,  0.3780,  3.0038,  1.6906,  2.7147, -0.5376,  2.4914, -2.0788,
          1.4909, -1.3881,  2.4724],
        [ 0.0640, -1.1329, -1.6580,  0.5247, -0.0684,  0.4544,  1.1120, -0.6181,
          1.3843,  0.4349,  1.0469,  1.3708,  1.2692, -0.3540,  0.3016, -1.3420,
          0.7071, -0.9681,  0.3206],
        [-0.0841, -1.1053, -

tensor([[ 9.5562e-01, -8.6491e-02, -2.8510e-01,  1.1598e-01,  1.3887e+00,
         -1.3598e+00,  2.3178e+00,  4.5104e-02,  2.5108e+00,  2.8226e-01,
          2.2416e+00,  2.0944e+00,  2.4869e+00,  1.9516e-01,  3.5877e+00,
         -4.6197e-01,  1.8103e+00, -5.8748e-02,  2.6619e+00],
        [-1.3027e-03, -8.5055e-01, -1.2166e+00,  1.0185e+00,  1.7344e+00,
          9.5238e-01,  1.1977e+00,  2.3970e-01,  2.2333e+00,  6.7695e-01,
          2.3174e+00,  2.2439e+00,  1.5260e+00,  1.5552e-01,  5.8629e-01,
         -2.4963e+00,  1.7468e+00, -1.9041e+00,  2.0899e+00],
        [ 9.5562e-01, -8.6491e-02, -2.8510e-01,  1.1598e-01,  1.3887e+00,
         -1.3598e+00,  2.3178e+00,  4.5104e-02,  2.5108e+00,  2.8226e-01,
          2.2416e+00,  2.0944e+00,  2.4869e+00,  1.9516e-01,  3.5877e+00,
         -4.6197e-01,  1.8103e+00, -5.8748e-02,  2.6619e+00],
        [-1.3027e-03, -8.5055e-01, -1.2166e+00,  1.0185e+00,  1.7344e+00,
          9.5238e-01,  1.1977e+00,  2.3970e-01,  2.2333e+00,  6.7695e-01,


tensor([[ 0.8927, -2.7120, -3.2434, -0.2860, -1.1441, -1.6254,  3.8686, -1.8621,
          2.8091,  1.9516,  1.8982,  3.6728,  0.2990,  0.4012,  1.7061, -2.2410,
          2.5154, -1.2692, -0.1636],
        [-0.4563,  0.3577, -0.9090,  1.0095,  1.9548,  0.1971,  1.3834,  0.2175,
          2.3886,  0.0545,  1.7350,  1.1221,  2.0278, -1.3669,  3.2522, -1.7795,
          2.3470, -1.1923,  3.8624],
        [ 0.9582, -2.1653, -3.5836,  1.0182,  0.4152,  2.4768,  1.4602, -0.0579,
          0.6229,  0.4587,  0.3304,  2.1484,  1.5337,  0.6407,  0.8530, -0.6133,
          2.0886, -1.3331, -0.1657],
        [ 0.8887, -1.1322, -0.3190,  0.4184,  0.1700, -0.5648,  2.8171, -0.0922,
          3.2821,  0.2447,  3.1833,  2.3734,  1.7827,  0.3079, -0.2969, -2.2902,
          0.2534, -2.0003,  1.3061]], grad_fn=<MmBackward0>)
tensor([[ 0.1498, -1.2866, -3.2226,  0.6422, -0.0892, -0.8076,  2.2966, -2.0985,
          3.3414,  1.5630,  1.1338,  4.5085, -2.3924,  0.3662,  1.8080, -2.5737,
          4.3548, 

tensor([[-0.0881, -0.2373, -1.7145,  1.1724,  1.5523,  0.9535, -0.9502, -1.0072,
          1.5392,  0.3888,  0.9081,  2.6970,  1.8131,  0.2971,  1.4862, -0.5512,
          1.7031, -0.5425,  1.2127],
        [ 0.7134, -0.4504, -0.2311,  0.7428,  0.3662,  0.1060,  2.8386,  0.4940,
          2.9651, -0.6761,  2.5875,  1.0298,  2.5561, -0.7878,  0.7749, -1.6555,
          0.1920, -1.8526,  2.3195],
        [-0.4659, -0.7914, -1.6742,  0.3278,  0.4884, -0.2281,  1.3721, -0.6054,
          1.4802,  1.1085,  0.9281,  1.5316, -0.3125, -0.5066,  1.3664, -2.0849,
          2.2339, -1.2318,  1.3866],
        [-0.0217, -1.6900, -1.8841,  0.3613,  0.7438,  0.5913,  1.8448,  0.0761,
          1.2510,  1.3824,  1.5571,  1.7493,  0.3299,  0.2554,  0.2612, -2.5643,
          1.8862, -1.5346,  0.7509]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<MmBackward0>)
tensor([[-0.1108, -0.7580, -2.7112,  1.4807,  1.5130,  1.0609, -0.0261, -1.3400,
          2.4538,  0.4455,  1.5484,  3.0974,  3.3415, -0.4697,  2.4797, -1.1726,
          2.0540, -0.7838,  1.8337],
        [ 0.0714,  0.2543, -0.4532,  0.2880,  0.5207,  0.1612,  0.4839,  0.1080,
          0.5434,  0.0179, -0.0820,  0.6789, -1.0807,  0.0845,  0.9840, -0.2737,
          1.5807, -0.8690,  1.1724],
        [ 0.5010, -1.0437, -1.5717,  0.9378,  1.8747, -0.2664,  2.2228, -0.4981,
          3.8039,  1.1878,  3.2865,  4.2082,  1.2977,  0.7474,  1.7347, -2.9200,
          2.9779, -2.3479,  2.7978],
        [ 0.0714,  0.2543, -

tensor([[ 1.0153, -0.8452, -3.4839,  1.7611,  4.4167,  2.5938,  1.1916,  1.0082,
          1.6458,  0.6288,  1.6176,  3.4516,  4.4707,  0.7812,  6.1303, -0.3007,
          5.0950, -0.4546,  4.1602],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315],
        [-0.3562, -1.1428, -1.0016,  0.5114, -0.8077, -0.8802,  2.9606, -0.9653,
          3.5831,  0.3811,  2.7997,  1.4299,  1.4128, -1.6509, -0.2625, -3.4735,
          0.1468, -2.3657,  1.5537],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315]], grad_fn=<MmBackward0>)
tensor([[ 3.0559e-01, -3.9922e-01, -2.7887e+00,  6.7077e-01,  7.7077e-01,
          8.4653e-01,  1.3264e+00, -3.5363e-01,  8.5761e-01,  7.3833e-01,
         -9.0896e-01,  2.4413e+0

tensor([[ 0.0694, -0.8341, -0.3852,  0.5840,  0.0441, -0.9188,  3.0367, -0.4092,
          3.8396,  0.0605,  3.4900,  1.4916,  3.1093, -1.4111,  0.6241, -2.9667,
         -0.0954, -1.8068,  2.2911],
        [-0.3076, -0.0782, -0.7465,  0.5466,  2.6054, -0.7077,  1.0510, -0.1006,
          2.4384,  1.3773,  2.3635,  2.7448,  0.9917,  0.2315,  2.9349, -2.3089,
          3.1407, -0.9532,  3.3069],
        [-0.6440, -0.9484, -2.2846,  0.9623,  1.0704,  1.7586, -0.1844, -0.2671,
          0.4570,  0.9373,  0.1944,  1.4817, -0.3535, -0.0424,  0.1815, -1.8207,
          2.1854, -1.5064,  0.7208],
        [ 0.7619, -0.6517, -1.0726,  0.5374,  0.9013,  0.8687,  0.3903,  0.0819,
          0.7328,  0.1384,  0.7543,  1.6752,  1.3457,  0.8831,  0.7724,  0.0105,
          0.9951, -0.3993,  0.4019]], grad_fn=<MmBackward0>)
tensor([[ 0.6294, -1.0481, -0.9788,  0.3619,  0.8847,  0.1738,  1.5575,  0.1050,
          1.6276,  0.6879,  1.7959,  2.0691,  1.1033,  0.7471,  0.5934, -1.3907,
          1.2837, 

tensor([[ 1.0153, -0.8452, -3.4839,  1.7611,  4.4167,  2.5938,  1.1916,  1.0082,
          1.6458,  0.6288,  1.6176,  3.4516,  4.4707,  0.7812,  6.1303, -0.3007,
          5.0950, -0.4546,  4.1602],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315],
        [-0.3562, -1.1428, -1.0016,  0.5114, -0.8077, -0.8802,  2.9606, -0.9653,
          3.5831,  0.3811,  2.7997,  1.4299,  1.4128, -1.6509, -0.2625, -3.4735,
          0.1468, -2.3657,  1.5537],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315]], grad_fn=<MmBackward0>)
tensor([[-3.7134e-01,  2.5626e-01, -1.6145e+00,  7.2774e-01,  1.1214e+00,
          2.9438e-01, -3.4819e-01, -8.2876e-01,  9.4423e-01,  3.8533e-01,
         -1.5202e-01,  1.6420e+0

tensor([[ 7.0422e-01, -1.9554e+00, -1.6819e+00, -2.1417e-01, -3.7632e-01,
          8.1945e-02,  2.2273e+00, -5.8142e-03,  5.3916e-01,  9.7774e-01,
          1.0179e+00,  1.0471e+00,  1.1073e+00,  4.2737e-01,  2.9153e-01,
         -1.0699e+00,  6.6203e-01, -3.4185e-01, -6.3674e-01],
        [-1.5822e+00,  3.0142e-01, -2.9448e+00,  2.4262e+00,  4.3233e+00,
          6.1079e-01,  4.1281e-01, -1.2428e+00,  4.8168e+00,  9.5997e-01,
          3.5338e+00,  3.8279e+00,  5.5394e+00, -2.4706e+00,  6.3921e+00,
         -3.6032e+00,  4.5571e+00, -1.4141e+00,  6.6356e+00],
        [ 7.2957e-01, -1.4395e+00, -1.8682e+00,  2.8193e-01,  4.5226e-01,
          8.3396e-01,  1.7132e+00,  2.4046e-01,  6.5603e-01,  7.6402e-01,
          6.7094e-01,  1.6517e+00,  5.7203e-02,  8.2707e-01,  6.5893e-01,
         -9.4810e-01,  1.8788e+00, -1.1079e+00,  2.5687e-01],
        [-2.0222e-02, -8.0607e-01, -1.0935e+00,  3.6691e-01, -5.2129e-01,
         -5.4204e-01,  2.3693e+00, -6.5475e-01,  2.4920e+00,  3.6052e-01,


tensor([[ 0.0321, -0.5227, -0.6618,  0.2065,  0.5519,  0.3733,  0.6273,  0.2275,
          0.3570,  0.2856,  0.6567,  0.2902,  1.3400, -0.1971,  0.7609, -0.5896,
          0.4531, -0.0537,  0.5554],
        [ 0.1500, -0.4448, -1.7728,  0.7936,  0.5099,  0.5358,  1.7347, -0.2357,
          1.8723,  0.1545,  0.7119,  1.6661, -0.3084, -0.4319,  1.6285, -1.3761,
          2.4893, -1.9493,  1.9791],
        [ 0.0321, -0.5227, -0.6618,  0.2065,  0.5519,  0.3733,  0.6273,  0.2275,
          0.3570,  0.2856,  0.6567,  0.2902,  1.3400, -0.1971,  0.7609, -0.5896,
          0.4531, -0.0537,  0.5554],
        [ 0.8337, -3.3170, -4.1394, -0.1767, -0.9823, -0.8286,  3.3557, -1.9099,
          2.0262,  2.1772,  1.5842,  3.4679,  1.7699,  0.3292,  2.0057, -1.8800,
          2.3042, -0.4447, -0.8843]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[ 0.5861, -0.8599, -0.9450, -0.1917, -0.1171, -0.6958,  1.4397, -0.4607,
          0.9899,  0.8358,  0.6658,  1.7737, -0.8006,  0.8275,  0.5945, -0.6984,
          1.4432, -0.6842,  0.0550],
        [-1.9165, -0.1060, -2.3901,  1.9809,  3.6305,  2.2449, -1.5859, -0.3252,
          1.5490,  1.0570,  1.6206,  1.7430,  3.6013, -1.5461,  2.7671, -2.8330,
          2.7484, -0.7891,  3.5642],
        [ 0.5861, -0.8599, -0.9450, -0.1917, -0.1171, -0.6958,  1.4397, -0.4607,
          0.9899,  0.8358,  0.6658,  1.7737, -0.8006,  0.8275,  0.5945, -0.6984,
          1.4432, -0.6842,  0.0550],
        [-1.9165, -0.1060, -2.3901,  1.9809,  3.6305,  2.2449, -1.5859, -0.3252,
          1.5490,  1.0570,  1.6206,  1.7430,  3.6013, -1.5461,  2.7671, -2.8330,
          2.7484, -0.7891,  3.5642]], grad_fn=<MmBackward0>)
tensor([[ 0.3977, -1.7518, -1.3778,  0.1853, -0.5495,  0.0649,  3.2927,  0.1537,
          1.9489,  0.5178,  1.9790,  0.8665,  1.1616, -0.5978, -0.1622, -2.4587,
          0.5001, 

tensor([[-0.1059, -0.7880, -3.5468,  1.3448, -0.0425,  1.6581,  0.5908, -1.3333,
          1.4838,  0.1543, -0.6116,  2.3608, -1.0521, -0.5381,  1.4527, -0.9179,
          3.1824, -2.2567,  1.0383],
        [ 0.0662, -0.3708, -1.0577,  0.3910,  0.0862,  0.1523,  0.5105, -0.5457,
          0.9791,  0.1949,  0.3819,  1.1578,  0.1964, -0.1156,  0.6605, -0.5622,
          0.9846, -0.7030,  0.5297],
        [ 1.2650, -2.5863, -2.4302, -0.3889,  0.0272, -1.7231,  4.2942, -0.8192,
          2.7753,  1.6900,  3.0114,  2.9445,  3.7409,  0.2040,  3.2432, -1.7480,
          1.7258,  0.1176,  0.7765],
        [ 0.0662, -0.3708, -1.0577,  0.3910,  0.0862,  0.1523,  0.5105, -0.5457,
          0.9791,  0.1949,  0.3819,  1.1578,  0.1964, -0.1156,  0.6605, -0.5622,
          0.9846, -0.7030,  0.5297]], grad_fn=<MmBackward0>)
tensor([[ 0.3437, -1.6203, -1.8009,  0.4553,  1.7203, -0.6562,  4.6266,  0.5716,
          3.5291,  1.1342,  3.8593,  1.8665,  4.3044, -1.2304,  3.9757, -3.3611,
          2.4758, 

tensor([[ 4.7172e-01, -1.6895e+00, -1.8998e+00,  1.1912e+00,  1.1933e+00,
          1.4764e+00,  1.7662e+00,  1.0907e-01,  2.4899e+00,  3.6864e-01,
          2.8090e+00,  2.2477e+00,  3.8412e+00, -1.0378e-01,  3.7934e-01,
         -2.2895e+00,  6.9816e-01, -1.6102e+00,  1.3585e+00],
        [-1.9605e-01, -9.5923e-01, -1.0331e+00,  8.1169e-02, -4.2439e-02,
         -8.1186e-01,  5.8467e-01, -1.2242e+00,  1.5515e+00,  1.0983e+00,
          1.3790e+00,  1.9437e+00,  7.2491e-01,  6.5883e-02,  1.5075e-01,
         -1.5701e+00,  5.9695e-01, -4.3395e-01,  2.8611e-03],
        [ 2.2021e-01, -1.1138e+00, -3.0937e+00,  1.6142e+00,  3.2697e+00,
          2.7354e+00,  1.1502e+00,  9.8554e-01,  1.2605e+00,  5.8303e-01,
          1.5041e+00,  2.0115e+00,  3.8434e+00, -1.9040e-01,  3.8624e+00,
         -1.3856e+00,  3.5473e+00, -9.3684e-01,  3.2201e+00],
        [ 1.0855e+00, -1.6392e+00, -1.3318e+00,  7.1761e-02,  6.4441e-01,
          2.9545e-01,  3.0780e+00,  7.8578e-01,  1.4741e+00,  1.1161e+00,


tensor([[-0.1750, -0.3123, -0.4822,  0.1411,  0.0184, -0.2045,  0.9127, -0.1808,
          0.9134,  0.3127,  0.6429,  0.5121, -0.1038, -0.3892,  0.2911, -1.1147,
          0.6689, -0.7893,  0.7102],
        [ 1.1511, -0.9250, -1.3372,  0.3156, -0.0460, -0.3598,  1.6615, -0.7750,
          2.0439,  0.2638,  1.2732,  2.7184,  0.7497,  0.8747,  1.0205, -0.3374,
          1.3083, -0.9681,  0.4142],
        [-0.1750, -0.3123, -0.4822,  0.1411,  0.0184, -0.2045,  0.9127, -0.1808,
          0.9134,  0.3127,  0.6429,  0.5121, -0.1038, -0.3892,  0.2911, -1.1147,
          0.6689, -0.7893,  0.7102],
        [ 0.2348, -1.1531, -4.2318,  1.7751,  1.8806,  0.8451,  2.1766, -1.5264,
          4.2113,  1.4034,  1.7654,  5.7620, -1.2651,  0.5123,  3.2923, -3.0840,
          6.2295, -3.9273,  3.6236]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[ 0.3580, -0.7445, -0.6131, -0.1348, -0.4008, -0.7397,  2.4445, -0.0047,
          1.4085,  0.3154,  1.1271,  0.5745,  0.2893, -0.4347,  0.8394, -1.2224,
          0.7576, -0.8913,  0.8628],
        [-0.8869, -1.2651, -2.7020,  0.5810,  0.2925,  0.0769,  1.7382, -0.9928,
          1.7913,  1.2906,  1.0360,  1.4472,  0.5856, -1.4418,  1.8816, -2.7613,
          2.4570, -1.3701,  1.6039],
        [ 1.4741, -1.0593, -0.8499,  0.6388,  1.0545,  0.4407,  1.7023,  0.1830,
          2.2513,  0.0777,  2.3711,  2.7960,  2.5853,  1.2958,  0.7292, -0.6161,
          0.8108, -1.0253,  0.9512],
        [-0.3994, -1.5278, -3.6727,  1.1101, -0.1913,  0.3596,  0.1655, -2.7253,
          2.5367,  1.2591,  0.8350,  3.9258,  0.4145, -0.2387,  0.9053, -1.9450,
          2.4350, -1.6327,  0.1723]], grad_fn=<MmBackward0>)
tensor([[ 0.5491,  0.8787,  0.0957,  0.7319,  3.4994,  0.1127,  1.0709,  1.3204,
          1.7955,  0.2033,  1.7839,  1.9792,  1.2504,  0.7266,  4.0296, -0.5760,
          3.4029, 

tensor([[-0.3433, -0.1743, -1.2748,  0.3542,  0.1061, -0.0909,  0.7551, -0.6208,
          1.0039,  0.3619,  0.0995,  0.8748, -0.4875, -0.6766,  1.3666, -0.9213,
          1.6860, -0.8614,  1.1370],
        [ 0.3317, -2.1533, -3.8927,  0.7024, -0.5503,  0.5381,  2.9809, -1.2235,
          2.2321,  0.9484,  0.9304,  2.4795,  0.8032, -0.7502,  1.9707, -2.0133,
          2.7775, -1.8772,  0.8172],
        [-0.3433, -0.1743, -1.2748,  0.3542,  0.1061, -0.0909,  0.7551, -0.6208,
          1.0039,  0.3619,  0.0995,  0.8748, -0.4875, -0.6766,  1.3666, -0.9213,
          1.6860, -0.8614,  1.1370],
        [ 1.2904, -2.5828, -3.7423,  0.8012,  0.6957,  0.6026,  1.8561, -1.3996,
          2.4041,  1.1756,  2.1806,  4.1264,  4.5194,  0.8161,  2.5663, -0.7936,
          1.9016, -0.1409,  0.0991]], grad_fn=<MmBackward0>)
tensor([[-0.3562, -1.1428, -1.0016,  0.5114, -0.8077, -0.8802,  2.9606, -0.9653,
          3.5831,  0.3811,  2.7997,  1.4299,  1.4128, -1.6509, -0.2625, -3.4735,
          0.1468, 

tensor([[ 0.0640, -1.1329, -1.6580,  0.5247, -0.0684,  0.4544,  1.1120, -0.6181,
          1.3843,  0.4349,  1.0469,  1.3708,  1.2692, -0.3540,  0.3016, -1.3420,
          0.7071, -0.9681,  0.3206],
        [-0.0841, -1.1053, -1.6892,  0.5942,  0.0302,  0.5215,  0.9057, -0.6877,
          1.4056,  0.4899,  1.0774,  1.4063,  1.3196, -0.4258,  0.2423, -1.4800,
          0.7138, -0.9888,  0.3695],
        [ 0.7533, -0.9046, -0.7475,  0.1401,  0.8960,  0.0853,  1.4806,  0.3648,
          1.0557,  0.5972,  1.4180,  1.5711,  1.1591,  0.8263,  0.9490, -0.7840,
          1.1617, -0.5071,  0.7568],
        [ 1.0421, -1.3354, -1.1182,  0.1676,  0.4093, -0.8924,  4.4559,  0.3825,
          3.1608,  0.3780,  3.0038,  1.6906,  2.7147, -0.5376,  2.4914, -2.0788,
          1.4909, -1.3881,  2.4724]], grad_fn=<MmBackward0>)
tensor([[-0.1108, -0.7580, -2.7112,  1.4807,  1.5130,  1.0609, -0.0261, -1.3400,
          2.4538,  0.4455,  1.5484,  3.0974,  3.3415, -0.4697,  2.4797, -1.1726,
          2.0540, 

tensor([[ 0.5215, -1.5781, -3.0804,  0.8819,  0.5836,  1.5339,  1.0269, -0.5534,
          1.0588,  0.8113,  0.3784,  2.6567,  0.1425,  0.7013,  0.9928, -1.0217,
          2.6635, -1.5356,  0.3379],
        [ 0.1419, -0.6096, -0.7971,  0.4118,  1.3086,  0.6666,  0.8972,  0.6055,
          0.6444,  0.3373,  1.2215,  0.5250,  2.4360, -0.1810,  1.4925, -0.8059,
          0.8089, -0.0279,  1.2817],
        [ 0.1498, -1.2866, -3.2226,  0.6422, -0.0892, -0.8076,  2.2966, -2.0985,
          3.3414,  1.5630,  1.1338,  4.5085, -2.3924,  0.3662,  1.8080, -2.5737,
          4.3548, -2.8932,  1.5504],
        [ 0.1419, -0.6096, -0.7971,  0.4118,  1.3086,  0.6666,  0.8972,  0.6055,
          0.6444,  0.3373,  1.2215,  0.5250,  2.4360, -0.1810,  1.4925, -0.8059,
          0.8089, -0.0279,  1.2817]], grad_fn=<MmBackward0>)
tensor([[ 0.6885, -1.3553, -1.9441,  0.7690,  0.2572,  1.6816,  1.0085,  0.1051,
          0.7111, -0.0102,  0.6854,  1.2192,  1.8520,  0.2450,  0.1639, -0.4892,
          0.6407, 

tensor([[ 0.4887, -0.6891, -0.5170,  0.0346, -0.1985, -0.2603,  1.6362, -0.0123,
          1.1488,  0.2021,  0.9886,  0.8794,  0.2982,  0.1110,  0.1908, -0.8462,
          0.4895, -0.8479,  0.4025],
        [ 0.4915, -0.9486, -2.2241,  0.9238,  1.4192,  0.9928,  0.7393, -0.3902,
          1.5531,  0.6106,  1.1368,  2.6751,  1.7115,  0.5284,  2.0049, -0.8039,
          2.3566, -0.8639,  1.3343],
        [ 0.2336, -0.7642, -0.8565,  0.7493,  1.3974, -0.0239,  1.7203, -0.0564,
          2.7287,  0.4375,  2.8384,  2.0367,  3.2906, -0.3419,  1.5724, -2.0117,
          0.9628, -0.9843,  2.2201],
        [-1.0499, -0.9169, -2.0951,  0.8313,  0.5382,  0.6172,  0.7399, -0.8139,
          1.6140,  1.0027,  1.0377,  1.3459,  0.3552, -1.1724,  0.6318, -2.7636,
          1.8124, -1.6405,  1.3941]], grad_fn=<MmBackward0>)
tensor([[-1.9171, -0.1065, -2.3915,  1.9808,  3.6289,  2.2449, -1.5861, -0.3265,
          1.5484,  1.0568,  1.6195,  1.7419,  3.6031, -1.5479,  2.7679, -2.8323,
          2.7473, 

tensor([[ 1.0153, -0.8452, -3.4839,  1.7611,  4.4167,  2.5938,  1.1916,  1.0082,
          1.6458,  0.6288,  1.6176,  3.4516,  4.4707,  0.7812,  6.1303, -0.3007,
          5.0950, -0.4546,  4.1602],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315],
        [-0.3562, -1.1428, -1.0016,  0.5114, -0.8077, -0.8802,  2.9606, -0.9653,
          3.5831,  0.3811,  2.7997,  1.4299,  1.4128, -1.6509, -0.2625, -3.4735,
          0.1468, -2.3657,  1.5537],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315]], grad_fn=<MmBackward0>)
tensor([[-7.2718e-01,  2.0212e-02, -1.1827e+00,  7.6999e-01,  1.0525e+00,
          6.3028e-02, -1.2487e-01, -8.5799e-01,  1.5680e+00,  4.5028e-01,
          9.4648e-01,  1.3580e+0

tensor([[ 2.2021e-01, -1.1138e+00, -3.0937e+00,  1.6142e+00,  3.2697e+00,
          2.7354e+00,  1.1502e+00,  9.8554e-01,  1.2605e+00,  5.8303e-01,
          1.5041e+00,  2.0115e+00,  3.8434e+00, -1.9040e-01,  3.8624e+00,
         -1.3856e+00,  3.5473e+00, -9.3684e-01,  3.2201e+00],
        [ 1.0855e+00, -1.6392e+00, -1.3318e+00,  7.1761e-02,  6.4441e-01,
          2.9545e-01,  3.0780e+00,  7.8578e-01,  1.4741e+00,  1.1161e+00,
          1.6373e+00,  2.2880e+00, -1.2364e+00,  1.4851e+00,  1.0749e-01,
         -2.0466e+00,  2.4892e+00, -2.2522e+00,  8.7137e-01],
        [ 4.7172e-01, -1.6895e+00, -1.8998e+00,  1.1912e+00,  1.1933e+00,
          1.4764e+00,  1.7662e+00,  1.0907e-01,  2.4899e+00,  3.6864e-01,
          2.8090e+00,  2.2477e+00,  3.8412e+00, -1.0378e-01,  3.7934e-01,
         -2.2895e+00,  6.9816e-01, -1.6102e+00,  1.3585e+00],
        [-1.9605e-01, -9.5923e-01, -1.0331e+00,  8.1169e-02, -4.2439e-02,
         -8.1186e-01,  5.8467e-01, -1.2242e+00,  1.5515e+00,  1.0983e+00,


tensor([[-0.1750, -0.3123, -0.4822,  0.1411,  0.0184, -0.2045,  0.9127, -0.1808,
          0.9134,  0.3127,  0.6429,  0.5121, -0.1038, -0.3892,  0.2911, -1.1147,
          0.6689, -0.7893,  0.7102],
        [ 0.2348, -1.1531, -4.2318,  1.7751,  1.8806,  0.8451,  2.1766, -1.5264,
          4.2113,  1.4034,  1.7654,  5.7620, -1.2651,  0.5123,  3.2923, -3.0840,
          6.2295, -3.9273,  3.6236],
        [-0.1750, -0.3123, -0.4822,  0.1411,  0.0184, -0.2045,  0.9127, -0.1808,
          0.9134,  0.3127,  0.6429,  0.5121, -0.1038, -0.3892,  0.2911, -1.1147,
          0.6689, -0.7893,  0.7102],
        [ 1.1511, -0.9250, -1.3372,  0.3156, -0.0460, -0.3598,  1.6615, -0.7750,
          2.0439,  0.2638,  1.2732,  2.7184,  0.7497,  0.8747,  1.0205, -0.3374,
          1.3083, -0.9681,  0.4142]], grad_fn=<MmBackward0>)
tensor([[-5.4484e-01, -2.6212e+00, -3.2857e+00,  4.9355e-01,  3.0628e-01,
         -1.4818e+00,  3.3829e+00, -2.1473e+00,  4.4003e+00,  2.4816e+00,
          3.8878e+00,  4.0193e+0

tensor([[ 0.5010, -1.0437, -1.5717,  0.9378,  1.8747, -0.2664,  2.2228, -0.4981,
          3.8039,  1.1878,  3.2865,  4.2082,  1.2977,  0.7474,  1.7347, -2.9200,
          2.9779, -2.3479,  2.7978],
        [ 0.0714,  0.2543, -0.4532,  0.2880,  0.5207,  0.1612,  0.4839,  0.1080,
          0.5434,  0.0179, -0.0820,  0.6789, -1.0807,  0.0845,  0.9840, -0.2737,
          1.5807, -0.8690,  1.1724],
        [-0.1108, -0.7580, -2.7112,  1.4807,  1.5130,  1.0609, -0.0261, -1.3400,
          2.4538,  0.4455,  1.5484,  3.0974,  3.3415, -0.4697,  2.4797, -1.1726,
          2.0540, -0.7838,  1.8337],
        [ 0.0714,  0.2543, -0.4532,  0.2880,  0.5207,  0.1612,  0.4839,  0.1080,
          0.5434,  0.0179, -0.0820,  0.6789, -1.0807,  0.0845,  0.9840, -0.2737,
          1.5807, -0.8690,  1.1724]], grad_fn=<MmBackward0>)
tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, 

tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436]], grad_fn=<MmBackward0>)
tensor([[-0.1108, -0.7580, -2.7112,  1.4807,  1.5130,  1.0609, -0.0261, -1.3400,
          2.4538,  0.4455,  1.5484,  3.0974,  3.3415, -0.4697,  2.4797, -1.1726,
          2.0540, 

tensor([[-0.3433, -0.1743, -1.2748,  0.3542,  0.1061, -0.0909,  0.7551, -0.6208,
          1.0039,  0.3619,  0.0995,  0.8748, -0.4875, -0.6766,  1.3666, -0.9213,
          1.6860, -0.8614,  1.1370],
        [ 0.3317, -2.1533, -3.8927,  0.7024, -0.5503,  0.5381,  2.9809, -1.2235,
          2.2321,  0.9484,  0.9304,  2.4795,  0.8032, -0.7502,  1.9707, -2.0133,
          2.7775, -1.8772,  0.8172],
        [-0.3433, -0.1743, -1.2748,  0.3542,  0.1061, -0.0909,  0.7551, -0.6208,
          1.0039,  0.3619,  0.0995,  0.8748, -0.4875, -0.6766,  1.3666, -0.9213,
          1.6860, -0.8614,  1.1370],
        [ 1.2904, -2.5828, -3.7423,  0.8012,  0.6957,  0.6026,  1.8561, -1.3996,
          2.4041,  1.1756,  2.1806,  4.1264,  4.5194,  0.8161,  2.5663, -0.7936,
          1.9016, -0.1409,  0.0991]], grad_fn=<MmBackward0>)
tensor([[ 0.5010, -1.0437, -1.5717,  0.9378,  1.8747, -0.2664,  2.2228, -0.4981,
          3.8039,  1.1878,  3.2865,  4.2082,  1.2977,  0.7474,  1.7347, -2.9200,
          2.9779, 

tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[ 0.5010, -1.0437, -1.5717,  0.9378,  1.8747, -0.2664,  2.2228, -0.4981,
          3.8039,  1.1878,  3.2865,  4.2082,  1.2977,  0.7474,  1.7347, -2.9200,
          2.9779, -2.3479,  2.7978],
        [ 0.0714,  0.2543, -0.4532,  0.2880,  0.5207,  0.1612,  0.4839,  0.1080,
          0.5434,  0.0179, -0.0820,  0.6789, -1.0807,  0.0845,  0.9840, -0.2737,
          1.5807, -0.8690,  1.1724],
        [-0.1108, -0.7580, -2.7112,  1.4807,  1.5130,  1.0609, -0.0261, -1.3400,
          2.4538,  0.4455,  1.5484,  3.0974,  3.3415, -0.4697,  2.4797, -1.1726,
          2.0540, -0.7838,  1.8337],
        [ 0.0714,  0.2543, -0.4532,  0.2880,  0.5207,  0.1612,  0.4839,  0.1080,
          0.5434,  0.0179, -0.0820,  0.6789, -1.0807,  0.0845,  0.9840, -0.2737,
          1.5807, -0.8690,  1.1724]], grad_fn=<MmBackward0>)
tensor([[-5.4484e-01, -2.6212e+00, -3.2857e+00,  4.9355e-01,  3.0628e-01,
         -1.4818e+00,  3.3829e+00, -2.1473e+00,  4.4003e+00,  2.4816e+00,
          3.8878e+00,  4.0193e+0

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<MmBackward0>)
tensor([[-0.1750, -0.3123, -0.4822,  0.1411,  0.0184, -0.2045,  0.9127, -0.1808,
          0.9134,  0.3127,  0.6429,  0.5121, -0.1038, -0.3892,  0.2911, -1.1147,
          0.6689, -0.7893,  0.7102],
        [ 1.1511, -0.9250, -1.3372,  0.3156, -0.046

tensor([[ 0.5010, -1.0437, -1.5717,  0.9378,  1.8747, -0.2664,  2.2228, -0.4981,
          3.8039,  1.1878,  3.2865,  4.2082,  1.2977,  0.7474,  1.7347, -2.9200,
          2.9779, -2.3479,  2.7978],
        [ 0.0714,  0.2543, -0.4532,  0.2880,  0.5207,  0.1612,  0.4839,  0.1080,
          0.5434,  0.0179, -0.0820,  0.6789, -1.0807,  0.0845,  0.9840, -0.2737,
          1.5807, -0.8690,  1.1724],
        [-0.1108, -0.7580, -2.7112,  1.4807,  1.5130,  1.0609, -0.0261, -1.3400,
          2.4538,  0.4455,  1.5484,  3.0974,  3.3415, -0.4697,  2.4797, -1.1726,
          2.0540, -0.7838,  1.8337],
        [ 0.0714,  0.2543, -0.4532,  0.2880,  0.5207,  0.1612,  0.4839,  0.1080,
          0.5434,  0.0179, -0.0820,  0.6789, -1.0807,  0.0845,  0.9840, -0.2737,
          1.5807, -0.8690,  1.1724]], grad_fn=<MmBackward0>)
tensor([[ 0.5861, -0.8599, -0.9450, -0.1917, -0.1171, -0.6958,  1.4397, -0.4607,
          0.9899,  0.8358,  0.6658,  1.7737, -0.8006,  0.8275,  0.5945, -0.6984,
          1.4432, 

tensor([[ 1.0153, -0.8452, -3.4839,  1.7611,  4.4167,  2.5938,  1.1916,  1.0082,
          1.6458,  0.6288,  1.6176,  3.4516,  4.4707,  0.7812,  6.1303, -0.3007,
          5.0950, -0.4546,  4.1602],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315],
        [-0.3562, -1.1428, -1.0016,  0.5114, -0.8077, -0.8802,  2.9606, -0.9653,
          3.5831,  0.3811,  2.7997,  1.4299,  1.4128, -1.6509, -0.2625, -3.4735,
          0.1468, -2.3657,  1.5537],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315]], grad_fn=<MmBackward0>)
tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, 

tensor([[-0.1750, -0.3123, -0.4822,  0.1411,  0.0184, -0.2045,  0.9127, -0.1808,
          0.9134,  0.3127,  0.6429,  0.5121, -0.1038, -0.3892,  0.2911, -1.1147,
          0.6689, -0.7893,  0.7102],
        [ 1.1511, -0.9250, -1.3372,  0.3156, -0.0460, -0.3598,  1.6615, -0.7750,
          2.0439,  0.2638,  1.2732,  2.7184,  0.7497,  0.8747,  1.0205, -0.3374,
          1.3083, -0.9681,  0.4142],
        [-0.1750, -0.3123, -0.4822,  0.1411,  0.0184, -0.2045,  0.9127, -0.1808,
          0.9134,  0.3127,  0.6429,  0.5121, -0.1038, -0.3892,  0.2911, -1.1147,
          0.6689, -0.7893,  0.7102],
        [ 0.2348, -1.1531, -4.2318,  1.7751,  1.8806,  0.8451,  2.1766, -1.5264,
          4.2113,  1.4034,  1.7654,  5.7620, -1.2651,  0.5123,  3.2923, -3.0840,
          6.2295, -3.9273,  3.6236]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[-0.1987, -0.8842, -1.3194,  0.2407,  0.3059,  0.1671,  0.6408, -0.4555,
          0.7796,  0.9410,  0.6369,  1.3558, -0.2696,  0.1394,  0.2243, -1.4363,
          1.3419, -0.8668,  0.2940],
        [-0.0995, -0.6998, -1.3002,  1.1762,  1.3869,  1.4671,  0.4128,  0.0769,
          1.6942,  0.1692,  1.7207,  1.5884,  2.3117, -0.2470,  0.3578, -1.7260,
          0.8994, -1.3735,  1.5172],
        [-0.1987, -0.8842, -1.3194,  0.2407,  0.3059,  0.1671,  0.6408, -0.4555,
          0.7796,  0.9410,  0.6369,  1.3558, -0.2696,  0.1394,  0.2243, -1.4363,
          1.3419, -0.8668,  0.2940],
        [ 1.9492, -2.3929, -3.2076,  1.5173,  1.5983,  1.7440,  3.8112,  0.3027,
          3.8024,  0.1844,  3.5663,  4.0649,  4.9456,  0.6921,  2.4111, -1.8406,
          2.3630, -2.2579,  2.3151]], grad_fn=<MmBackward0>)
tensor([[ 7.2957e-01, -1.4395e+00, -1.8682e+00,  2.8193e-01,  4.5226e-01,
          8.3396e-01,  1.7132e+00,  2.4046e-01,  6.5603e-01,  7.6402e-01,
          6.7094e-01,  1.6517e+0

tensor([[ 7.2957e-01, -1.4395e+00, -1.8682e+00,  2.8193e-01,  4.5226e-01,
          8.3396e-01,  1.7132e+00,  2.4046e-01,  6.5603e-01,  7.6402e-01,
          6.7094e-01,  1.6517e+00,  5.7203e-02,  8.2707e-01,  6.5893e-01,
         -9.4810e-01,  1.8788e+00, -1.1079e+00,  2.5687e-01],
        [-1.5822e+00,  3.0142e-01, -2.9448e+00,  2.4262e+00,  4.3233e+00,
          6.1079e-01,  4.1281e-01, -1.2428e+00,  4.8168e+00,  9.5997e-01,
          3.5338e+00,  3.8279e+00,  5.5394e+00, -2.4706e+00,  6.3921e+00,
         -3.6032e+00,  4.5571e+00, -1.4141e+00,  6.6356e+00],
        [ 7.0422e-01, -1.9554e+00, -1.6819e+00, -2.1417e-01, -3.7632e-01,
          8.1945e-02,  2.2273e+00, -5.8142e-03,  5.3916e-01,  9.7774e-01,
          1.0179e+00,  1.0471e+00,  1.1073e+00,  4.2737e-01,  2.9153e-01,
         -1.0699e+00,  6.6203e-01, -3.4185e-01, -6.3674e-01],
        [-2.0222e-02, -8.0607e-01, -1.0935e+00,  3.6691e-01, -5.2129e-01,
         -5.4204e-01,  2.3693e+00, -6.5475e-01,  2.4920e+00,  3.6052e-01,


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<MmBackward0>)
tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -

tensor([[-0.0521,  0.0792,  0.0336,  1.1369,  2.4560,  0.6028,  1.8743,  1.1755,
          2.7899, -0.4181,  3.2865,  0.5717,  5.0451, -1.4257,  2.5485, -2.0593,
          0.5807, -0.8895,  4.0463],
        [ 0.1576, -0.6219, -1.5914,  0.0978, -0.1295, -0.8048,  1.8020, -0.8707,
          1.6101,  0.6941,  0.5786,  1.6923, -0.4371, -0.2950,  1.9602, -1.0196,
          2.1601, -0.9027,  1.1206],
        [ 0.1540, -0.6103, -1.5928,  0.1009, -0.1128, -0.7872,  1.7461, -0.8750,
          1.5760,  0.6956,  0.5488,  1.6956, -0.4449, -0.2750,  1.9613, -0.9858,
          2.1639, -0.8771,  1.1011],
        [ 1.2314, -2.2712, -2.5943,  0.6473,  0.3611,  0.6924,  1.5541, -0.9218,
          2.1103,  1.0633,  2.0209,  3.8410,  1.9888,  1.5220,  0.1464, -1.2755,
          1.3939, -1.2191, -0.4418]], grad_fn=<MmBackward0>)
tensor([[-3.7134e-01,  2.5626e-01, -1.6145e+00,  7.2774e-01,  1.1214e+00,
          2.9438e-01, -3.4819e-01, -8.2876e-01,  9.4423e-01,  3.8533e-01,
         -1.5202e-01,  1.6420e+0

tensor([[ 3.0559e-01, -3.9922e-01, -2.7887e+00,  6.7077e-01,  7.7077e-01,
          8.4653e-01,  1.3264e+00, -3.5363e-01,  8.5761e-01,  7.3833e-01,
         -9.0896e-01,  2.4413e+00, -3.3861e+00,  6.3258e-01,  2.4647e+00,
         -6.7589e-01,  4.8143e+00, -2.1983e+00,  1.7528e+00],
        [ 1.9855e-01, -4.3939e-01, -2.7383e-01,  4.3794e-01,  5.1186e-01,
          6.0098e-01,  1.0093e+00,  5.0415e-01,  9.6096e-01, -1.4788e-01,
          1.2125e+00,  2.9466e-01,  1.5962e+00, -2.8462e-01,  9.7142e-02,
         -9.3723e-01,  1.1225e-03, -7.3739e-01,  9.0130e-01],
        [-5.4484e-01, -2.6212e+00, -3.2857e+00,  4.9355e-01,  3.0628e-01,
         -1.4818e+00,  3.3829e+00, -2.1473e+00,  4.4003e+00,  2.4816e+00,
          3.8878e+00,  4.0193e+00,  2.9033e+00, -1.1124e+00,  2.0875e+00,
         -4.7540e+00,  2.4380e+00, -1.7272e+00,  1.8074e+00],
        [ 1.9855e-01, -4.3939e-01, -2.7383e-01,  4.3794e-01,  5.1186e-01,
          6.0098e-01,  1.0093e+00,  5.0415e-01,  9.6096e-01, -1.4788e-01,


tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436]], grad_fn=<MmBackward0>)
tensor([[ 0.5215, -1.5781, -3.0804,  0.8819,  0.5836,  1.5339,  1.0269, -0.5534,
          1.0588,  0.8113,  0.3784,  2.6567,  0.1425,  0.7013,  0.9928, -1.0217,
          2.6635, 

tensor([[-0.2411,  0.2712, -0.5386,  0.9234,  1.2399, -0.0389,  1.8834,  0.1765,
          2.7405, -0.3320,  2.0226,  0.8375,  2.2931, -1.5788,  2.4930, -1.8023,
          1.4171, -1.4024,  3.5137],
        [ 0.4805, -0.0363,  0.4776,  0.9062,  3.2954, -0.7612,  1.9104,  0.5412,
          4.2478,  0.9447,  4.5262,  3.9680,  2.0193,  1.1091,  1.7187, -3.1914,
          2.4552, -2.2115,  4.2142],
        [ 0.1561, -0.7659, -1.3480,  0.6506,  0.3677,  1.0078,  0.1305, -0.3276,
          0.7209,  0.1400,  0.5929,  1.1559,  1.4259,  0.0417,  0.1765, -0.5342,
          0.4773, -0.5441,  0.1197],
        [ 0.1520, -0.7622, -1.3559,  0.6492,  0.3776,  1.0174,  0.0958, -0.3316,
          0.6915,  0.1473,  0.5672,  1.1564,  1.4144,  0.0548,  0.1843, -0.5120,
          0.4875, -0.5227,  0.1034]], grad_fn=<MmBackward0>)
tensor([[-1.9171, -0.1065, -2.3915,  1.9808,  3.6289,  2.2449, -1.5861, -0.3265,
          1.5484,  1.0568,  1.6195,  1.7419,  3.6031, -1.5479,  2.7679, -2.8323,
          2.7473, 

tensor([[-2.2054e-01, -8.4806e-02,  6.7074e-02,  3.1387e-01,  2.3306e-01,
         -1.5353e-01,  9.2324e-01,  5.0106e-02,  1.3523e+00, -2.7638e-02,
          1.2510e+00,  2.9903e-01,  8.1367e-01, -6.7222e-01,  3.2952e-02,
         -1.3515e+00,  2.8335e-02, -9.0595e-01,  1.1554e+00],
        [ 2.2957e-01, -2.0351e+00, -5.4284e+00,  9.4447e-01,  4.8073e-01,
          8.0736e-01,  2.4996e+00, -1.6496e+00,  1.8899e+00,  1.4857e+00,
          3.9628e-03,  3.4194e+00,  6.4643e-01, -6.3037e-01,  4.8268e+00,
         -1.3157e+00,  5.2121e+00, -1.2874e+00,  1.7031e+00],
        [ 5.8009e-01, -7.5492e-01, -3.0353e-01,  2.7171e-01,  8.4104e-01,
         -3.4597e-01,  2.3734e+00,  4.5737e-01,  2.1622e+00,  2.9561e-01,
          2.4393e+00,  1.3073e+00,  2.1981e+00, -6.5681e-02,  1.1125e+00,
         -1.6350e+00,  6.8380e-01, -9.6078e-01,  1.7595e+00],
        [-2.1941e-01, -7.2367e-02,  7.7942e-02,  3.1978e-01,  2.5832e-01,
         -1.5187e-01,  9.1838e-01,  6.0206e-02,  1.3605e+00, -3.4208e-02,


tensor([[ 1.2650, -2.5863, -2.4302, -0.3889,  0.0272, -1.7231,  4.2942, -0.8192,
          2.7753,  1.6900,  3.0114,  2.9445,  3.7409,  0.2040,  3.2432, -1.7480,
          1.7258,  0.1176,  0.7765],
        [ 0.0662, -0.3708, -1.0577,  0.3910,  0.0862,  0.1523,  0.5105, -0.5457,
          0.9791,  0.1949,  0.3819,  1.1578,  0.1964, -0.1156,  0.6605, -0.5622,
          0.9846, -0.7030,  0.5297],
        [-0.1059, -0.7880, -3.5468,  1.3448, -0.0425,  1.6581,  0.5908, -1.3333,
          1.4838,  0.1543, -0.6116,  2.3608, -1.0521, -0.5381,  1.4527, -0.9179,
          3.1824, -2.2567,  1.0383],
        [ 0.0662, -0.3708, -1.0577,  0.3910,  0.0862,  0.1523,  0.5105, -0.5457,
          0.9791,  0.1949,  0.3819,  1.1578,  0.1964, -0.1156,  0.6605, -0.5622,
          0.9846, -0.7030,  0.5297]], grad_fn=<MmBackward0>)
tensor([[ 5.9500e-01, -1.9141e+00, -2.9064e+00,  2.0858e-01, -1.2779e+00,
         -8.5904e-02,  3.4946e+00, -8.5532e-01,  1.9172e+00,  6.0822e-01,
          7.3729e-01,  1.6128e+0

tensor([[-0.3404, -0.5003, -2.5505,  0.8848, -0.0284,  1.0049,  0.8651, -0.7946,
          1.0740,  0.1564, -0.4262,  1.1603, -0.6904, -0.9699,  1.5605, -0.9845,
          2.4559, -1.5993,  1.2337],
        [-1.3002,  0.1500, -1.8270,  1.7858,  3.2733,  1.1359, -2.2005, -1.2779,
          2.1898,  0.8251,  2.0337,  2.8296,  4.7381, -0.8736,  2.9446, -1.6505,
          1.8221,  0.1734,  2.8587],
        [ 1.2660, -2.2227, -1.5929, -0.1120, -0.0547, -1.1282,  3.3248, -0.6926,
          2.8619,  1.4807,  2.9090,  3.5627,  1.1114,  1.2964,  0.4382, -2.2168,
          1.4589, -1.4283,  0.2170],
        [ 0.3106, -0.4238, -1.3902,  0.6125, -0.1194,  0.3685,  1.3768, -0.4578,
          1.6409,  0.0389,  0.4122,  1.6985, -1.2230,  0.0185,  0.4272, -1.0570,
          1.8568, -2.0324,  1.0422]], grad_fn=<MmBackward0>)
tensor([[ 1.0153, -0.8452, -3.4839,  1.7611,  4.4167,  2.5938,  1.1916,  1.0082,
          1.6458,  0.6288,  1.6176,  3.4516,  4.4707,  0.7812,  6.1303, -0.3007,
          5.0950, 

tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436]], grad_fn=<MmBackward0>)
tensor([[-0.0881, -0.2373, -1.7145,  1.1724,  1.5523,  0.9535, -0.9502, -1.0072,
          1.5392,  0.3888,  0.9081,  2.6970,  1.8131,  0.2971,  1.4862, -0.5512,
          1.7031, 

tensor([[ 1.1683, -2.2508, -2.9040,  0.5205, -1.3018, -0.1128,  5.1423, -0.5893,
          3.5330,  0.2251,  2.1659,  2.2880,  1.0673, -0.8378,  1.2456, -2.4692,
          1.8738, -2.8967,  1.3149],
        [-0.3413, -0.1895, -1.3290,  0.2249,  0.3665, -0.1904,  0.4227, -0.6603,
          0.6757,  0.7056, -0.1036,  1.1654, -0.9749, -0.2203,  1.5161, -0.7779,
          2.0998, -0.6221,  0.9545],
        [ 0.8873, -2.3985, -3.7740,  1.2377,  1.4903,  1.8145,  1.1156, -0.7507,
          1.8453,  0.9770,  2.0073,  3.4794,  5.0199,  0.5402,  2.3480, -0.9846,
          1.8825, -0.2652,  0.5322],
        [-0.3413, -0.1895, -1.3290,  0.2249,  0.3665, -0.1904,  0.4227, -0.6603,
          0.6757,  0.7056, -0.1036,  1.1654, -0.9749, -0.2203,  1.5161, -0.7779,
          2.0998, -0.6221,  0.9545]], grad_fn=<MmBackward0>)
tensor([[-3.7134e-01,  2.5626e-01, -1.6145e+00,  7.2774e-01,  1.1214e+00,
          2.9438e-01, -3.4819e-01, -8.2876e-01,  9.4423e-01,  3.8533e-01,
         -1.5202e-01,  1.6420e+0

tensor([[ 1.0153, -0.8452, -3.4839,  1.7611,  4.4167,  2.5938,  1.1916,  1.0082,
          1.6458,  0.6288,  1.6176,  3.4516,  4.4707,  0.7812,  6.1303, -0.3007,
          5.0950, -0.4546,  4.1602],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315],
        [-0.3562, -1.1428, -1.0016,  0.5114, -0.8077, -0.8802,  2.9606, -0.9653,
          3.5831,  0.3811,  2.7997,  1.4299,  1.4128, -1.6509, -0.2625, -3.4735,
          0.1468, -2.3657,  1.5537],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315]], grad_fn=<MmBackward0>)
tensor([[-0.4435, -1.0877, -3.4663,  1.1024, -0.3405,  0.5684,  0.3854, -2.2881,
          2.1562,  0.8170,  0.1695,  3.0966, -0.5034, -0.5970,  1.1304, -1.6219,
          2.6786, 

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<MmBackward0>)
tensor([[ 0.2006, -1.4757, -0.5255, -0.0829, -0.0614, -1.2729,  3.6104, -0.0287,
          2.9165,  1.0171,  3.1509,  1.4713,  1.3761, -0.5327,  0.2545, -3.2850,
          0.6020, -1.6988,  1.4845],
        [-0.1556, -0.3133, -0.6936,  0.7279,  0.957

tensor([[ 0.7046, -1.4623, -2.4969,  0.1123, -0.6859, -0.4842,  2.3920, -1.1257,
          1.6698,  0.7220,  0.6283,  2.1405,  0.4037, -0.0547,  1.8928, -0.7433,
          1.9818, -0.8209,  0.2758],
        [ 0.4452,  0.0527, -0.5145,  0.7101,  1.3909,  0.3622,  0.9359,  0.2831,
          1.6953, -0.0975,  1.3381,  1.5742,  1.2593,  0.1705,  1.6637, -0.6527,
          1.5269, -0.9716,  2.1001],
        [-1.0827,  0.3521, -2.5952,  1.5861,  2.1013,  0.9864, -1.6986, -1.7322,
          1.8203,  0.8317,  0.1718,  3.2604,  0.0400, -0.3602,  2.7109, -1.2308,
          3.7054, -1.1965,  2.4483],
        [ 0.8796, -2.1575, -1.9395,  0.5881,  0.6199,  1.0182,  2.1281,  0.1191,
          1.7884,  0.9057,  2.2950,  2.4620,  2.1078,  0.8827, -0.2535, -2.0153,
          0.9736, -1.5057,  0.1911]], grad_fn=<MmBackward0>)
tensor([[ 4.7545e-01, -2.4057e+00, -3.7873e+00,  1.1423e+00,  6.7305e-01,
          1.9384e+00,  9.6851e-01, -9.3123e-01,  1.4950e+00,  1.1502e+00,
          1.2290e+00,  3.2618e+0

tensor([[-0.3562, -1.1428, -1.0016,  0.5114, -0.8077, -0.8802,  2.9606, -0.9653,
          3.5831,  0.3811,  2.7997,  1.4299,  1.4128, -1.6509, -0.2625, -3.4735,
          0.1468, -2.3657,  1.5537],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315],
        [ 1.0153, -0.8452, -3.4839,  1.7611,  4.4167,  2.5938,  1.1916,  1.0082,
          1.6458,  0.6288,  1.6176,  3.4516,  4.4707,  0.7812,  6.1303, -0.3007,
          5.0950, -0.4546,  4.1602],
        [ 0.2903, -0.5804, -0.2276,  0.0831,  0.0757,  0.0865,  1.4396,  0.4126,
          0.8477,  0.1924,  0.9674,  0.4645,  0.0239,  0.0995, -0.2652, -1.1125,
          0.3964, -1.0295,  0.5315]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185]], grad_fn=<MmBackward0>)
tensor([[-7.2718e-01,  2.0212e-02, -1.1827e+00,  7.6999e-01,  1.0525e+00,
          6.3028e-02, -1.2487e-01, -8.5799e-01,  1.5680e+00,  4.5028e-01,
          9.4648e-01,  1.3580e+0

tensor([[-0.6586,  0.4346, -0.0528,  0.7342,  1.8833,  0.1510, -0.3477,  0.0082,
          1.4463,  0.3768,  1.4618,  1.1349,  1.3521, -0.4045,  1.2759, -1.4583,
          1.1689, -0.5851,  2.2874],
        [ 1.4291, -1.3918, -0.9962,  0.7110,  0.6820,  0.8078,  2.3165,  0.4353,
          2.3645,  0.0118,  2.5018,  2.4892,  2.1803,  1.0604, -0.0995, -1.2678,
          0.6411, -1.7610,  0.8594],
        [-0.5632, -0.8821, -2.4632,  0.4218,  0.2249, -0.5460,  0.9038, -1.6350,
          1.7670,  1.3004,  0.6590,  2.3038,  0.0444, -0.6524,  2.1323, -1.7351,
          2.5795, -0.8210,  1.1105],
        [-0.0501, -0.6641, -1.3659,  0.4862,  0.9267,  0.4642,  0.7905, -0.1082,
          0.9903,  0.6481,  0.8638,  1.3268,  0.8062, -0.0537,  1.2576, -1.1813,
          1.6337, -0.7195,  1.1391]], grad_fn=<MmBackward0>)
tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, 

tensor([[ 1.2650, -2.5863, -2.4302, -0.3889,  0.0272, -1.7231,  4.2942, -0.8192,
          2.7753,  1.6900,  3.0114,  2.9445,  3.7409,  0.2040,  3.2432, -1.7480,
          1.7258,  0.1176,  0.7765],
        [ 0.0662, -0.3708, -1.0577,  0.3910,  0.0862,  0.1523,  0.5105, -0.5457,
          0.9791,  0.1949,  0.3819,  1.1578,  0.1964, -0.1156,  0.6605, -0.5622,
          0.9846, -0.7030,  0.5297],
        [-0.1059, -0.7880, -3.5468,  1.3448, -0.0425,  1.6581,  0.5908, -1.3333,
          1.4838,  0.1543, -0.6116,  2.3608, -1.0521, -0.5381,  1.4527, -0.9179,
          3.1824, -2.2567,  1.0383],
        [ 0.0662, -0.3708, -1.0577,  0.3910,  0.0862,  0.1523,  0.5105, -0.5457,
          0.9791,  0.1949,  0.3819,  1.1578,  0.1964, -0.1156,  0.6605, -0.5622,
          0.9846, -0.7030,  0.5297]], grad_fn=<MmBackward0>)
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        

tensor([[-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 1.1262, -1.6707, -0.8557, -0.5748, -0.8194, -2.2019,  3.6068, -0.8809,
          2.7857,  1.2517,  2.4645,  2.8015,  0.0755,  0.8277,  0.5843, -1.8812,
          1.1238, -1.1813,  0.2185],
        [-0.8113, -0.3084, -1.2919,  1.1446,  1.6953,  1.2967,  0.2561,  0.1656,
          1.3897,  0.2519,  1.4429,  0.6376,  2.6771, -1.2848,  1.4546, -1.9468,
          1.1546, -0.8870,  2.3103],
        [ 0.8386, -2.1398, -3.0723,  1.0672,  0.8691,  3.1868,  1.1563,  0.7659,
          0.0307,  0.4924,  0.3302,  1.6626,  0.8360,  1.0418, -0.3151, -1.0104,
          1.9044, -1.7584, -0.2436]], grad_fn=<MmBackward0>)
tensor([[ 2.2021e-01, -1.1138e+00, -3.0937e+00,  1.6142e+00,  3.2697e+00,
          2.7354e+00,  1.1502e+00,  9.8554e-01,  1.2605e+00,  5.8303e-01,
          1.5041e+00,  2.0115e+0

tensor([[ 4.7545e-01, -2.4057e+00, -3.7873e+00,  1.1423e+00,  6.7305e-01,
          1.9384e+00,  9.6851e-01, -9.3123e-01,  1.4950e+00,  1.1502e+00,
          1.2290e+00,  3.2618e+00,  2.0956e+00,  6.2091e-01,  6.2404e-01,
         -1.6431e+00,  2.1069e+00, -1.3898e+00, -1.2850e-01],
        [ 2.9986e-01, -1.1061e+00, -1.6596e+00,  4.5109e-01,  4.0603e-01,
          3.4644e-01,  1.3586e+00, -3.4779e-01,  1.3494e+00,  5.3309e-01,
          1.1814e+00,  1.5257e+00,  1.6765e+00, -1.1652e-01,  1.1772e+00,
         -1.0878e+00,  1.1546e+00, -6.4779e-01,  7.1770e-01],
        [-3.7134e-01,  2.5626e-01, -1.6145e+00,  7.2774e-01,  1.1214e+00,
          2.9438e-01, -3.4819e-01, -8.2876e-01,  9.4423e-01,  3.8533e-01,
         -1.5202e-01,  1.6420e+00, -2.1532e-03, -3.2358e-01,  2.5490e+00,
         -2.7617e-01,  2.5529e+00, -4.3512e-01,  1.6996e+00],
        [ 6.4488e-01, -2.0698e+00, -2.7124e+00,  7.7396e-02, -1.4364e+00,
         -5.3695e-01,  4.0264e+00, -9.0030e-01,  2.3591e+00,  7.1366e-01,


KeyboardInterrupt: 

In [4]:
trainer, model, module = generate_trainer(
    datafiles=datafiles[0:2],
    labelfiles=labelfiles[0:2],
    class_label='Type',
    skip=3,
    normalize=True,
    drop_last=True,
    batch_size=4,
    num_workers=0,
    wandb_name='local-model',
    weighted_metrics=True,
    optim_params={
        'optimizer': torch.optim.SGD,
        'lr': 0.001,
    },
    max_epochs=100,
)

Device is cpu
../data/interim/primary_bhaduri_T.csv exists, continuing...
../data/processed/labels/primary_bhaduri_labels.csv exists, continuing...

../data/interim/allen_cortex_T.csv exists, continuing...
../data/processed/labels/allen_cortex_labels.csv exists, continuing...



GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs


Model initialized. input_dim = 16604, output_dim = 19. Metrics are dict_keys(['accuracy', 'precision', 'recall']) and weighted_metrics = True


In [5]:
trainer.fit(model, datamodule=module)

Creating train/val/test DataLoaders...


/Users/julian/miniconda3/envs/base-data-science/lib/python3.9/site-packages/pytorch_lightning/loggers/wandb.py:341: UserWarning: There is a wandb run already in progress and newly created instances of `WandbLogger` will reuse this run. If this is not desired, call `wandb.finish()` before instantiating `WandbLogger`.
  rank_zero_warn(

  | Name       | Type                 | Params
----------------------------------------------------
0 | base_model | TabNetGeneClassifier | 1.1 M 
----------------------------------------------------
1.1 M     Trainable params
0         Non-trainable params
1.1 M     Total params
4.407     Total estimated model params size (MB)


Done, continuing to training.


Validation sanity check: 0it [00:00, ?it/s]

Training: 0it [00:00, ?it/s]

/Users/julian/miniconda3/envs/base-data-science/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py:685: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")


First, we'll define our train, val and test sets, then generate the associated DataLoaders and try training.

## PyTorch-Lightning compatible TabNet architecture 

In [3]:
data = GeneExpressionData(datafiles[0], labelfiles[0], 'Type', indices=range(0, 20))

train, val, test = generate_single_dataset(datafiles[0], labelfiles[0], 'Type')
train

GeneExpressionData(filename=../data/interim/primary_bhaduri_T.csv, labelname=../data/processed/labels/primary_bhaduri_labels.csv)

In [4]:
train = DataLoader(Subset(train, range(0, 50)), batch_size=4)
val = DataLoader(Subset(val, range(0, 50)), batch_size=4)
test = DataLoader(Subset(test, range(0, 50)), batch_size=4)

In [5]:
model = GeneClassifier(input_dim=19765, output_dim=19)

model.optim_params

Model initialized. input_dim = 19765, output_dim = 19. Metrics are dict_keys(['accuracy', 'precision', 'recall']) and weighted_metrics = False


{'optimizer': torch.optim.adam.Adam, 'lr': 0.001, 'weight_decay': 0.01}

In [6]:
from pytorch_lightning import Trainer 
from pytorch_lightning.loggers import WandbLogger
from models.lib.neural import GeneClassifier

wandb_logger = WandbLogger(project='TabNet Cell Type Classifier', name='Tabnet with Metrics')
trainer = Trainer(logger=wandb_logger)

trainer.fit(model, train, val)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
wandb: Currently logged in as: jlehrer1 (use `wandb login --relogin` to force relogin)



  | Name       | Type                 | Params
----------------------------------------------------
0 | base_model | TabNetGeneClassifier | 1.3 M 
----------------------------------------------------
1.3 M     Trainable params
0         Non-trainable params
1.3 M     Total params
5.241     Total estimated model params size (MB)


Validation sanity check: 0it [00:00, ?it/s]

/Users/julian/miniconda3/envs/base-data-science/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:111: UserWarning: The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/Users/julian/miniconda3/envs/base-data-science/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:111: UserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 10 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/Users/julian/miniconda3/envs/base-data-science/lib/python3.9/site-packages/pytorch_lightning/trainer/data_loading.py:407: UserWarning: The number of training samples (13) is smaller than th

Training: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ConnectionError), entering retry loop.
wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ConnectionError), entering retry loop.
wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ReadTimeout), entering retry loop.


In [2]:
from models.lib.lightning_train import *

In [ ]:
trainer, model, module = generate_trainer(
    
)

In [ ]:
prepare_data('../data')

In [ ]:
t.keys

In [ ]:
t.values()